Rename 'scope' to 'loop_scope' in error message
pytest-dev/pytest-asyncio pull request #1004
Opened 2024-12-02 21:36 UTC by tusharsadhwani

Ensures that when a wrong argument is passed, the non-deprecated `loop_scope` keyword arg is recommended.

2024-12-05 20:26 UTC, seifertm requested changes
Thanks for pointing this out!
Would you be willing to adjust the tests accordingly and add an entry to the changelog? Or would you prefer one of the maintainers take care of it?

2024-12-05 20:33 UTC, tusharsadhwani commented
I can do that. Let me fix the tests too.

2024-12-05 21:12 UTC, tusharsadhwani commented
@seifertm how's this?

2024-12-06 14:19 UTC, seifertm approved these changes
Perfect!
I squashed the commits and we can merge.

Thanks for the contribution!

2024-12-06 14:26 UTC, merged