Improve output with invalid asyncio_mode
pytest-dev/pytest-asyncio pull request #557
Opened 2023-06-06 10:04 UTC by The-Compiler

Instead of a long INTERNALERROR> stack trace, output a proper error
message:

    $ pytest -o asyncio_mode=True
    =================== test session starts ====================
    platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
    ERROR: 'True' is not a valid asyncio_mode

See https://github.com/pytest-dev/pytest/issues/11083

2023-06-06 10:08 UTC, The-Compiler commented
The Python 3.12 failure is unrelated:

```
ImportError while loading conftest '/home/runner/work/pytest-asyncio/pytest-asyncio/tests/conftest.py'.
  /usr/lib/python3.12/ast.py:407: in visit
      return visitor(node)
  /usr/lib/python3.12/ast.py:407: in visit
      return visitor(node)
  /usr/lib/python3.12/ast.py:407: in visit
      return visitor(node)
  /usr/lib/python3.12/ast.py:584: in _new
      warnings._deprecated(
  /usr/lib/python3.12/warnings.py:5[29](https://github.com/pytest-dev/pytest-asyncio/actions/runs/5187238300/jobs/9349366651?pr=557#step:6:30): in _deprecated
      warn(msg, DeprecationWarning, stacklevel=3)
  E   DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
```

see https://github.com/pytest-dev/pytest/issues/10977

2023-06-06 15:13 UTC, seifertm requested changes
Thanks for the PR! This definitely makes sense.

Could you also add an entry to `docs/source/reference/changelog.rst`? The new version can just be `0.22.0 (UNRELEASED)`

2023-06-06 15:13 UTC, seifertm commented on pytest_asyncio/plugin.py
> +        raise pytest.UsageError(f"{val!r} is not a valid asyncio_mode")
I think it would be helpful if the user got a list of valid _asyncio_mode_ values in the error message. For example:
```
True is not a valid asyncio_mode. Valid modes are "strict" and "auto".
```

2023-06-06 15:32 UTC, seifertm commented
I adjusted the warnings filters so that the DeprecationWarnings on Python 3.12 are ignored. The CI should be green as soon as you rebase your branch.

2023-06-06 17:14 UTC, The-Compiler commented
Improved and rebased!

2023-06-07 05:41 UTC, seifertm commented
Great, thank you for the quick turnaround!

2023-06-07 05:42 UTC, merged